server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rafaelcam/delivery-configs
          #uri: https://github.com/luhanlacerda/delivery-configs

